---
title: "R Notebook"
output: 
  html_document: 
    number_sections: true
    highlight: textmate
    theme: spacelab
    toc: yes
editor_options: 
  chunk_output_type: inline
---

# Loading library
```{r}
library(readxl)
options(stringsAsFactors = FALSE)
```


# Loading data
```{r}
rawdata <- read_excel("data/WORLD-MACHE_Gender_6.8.15.xls", "Sheet1", col_names=T)
```


# Summarize data

```{r}
# select 1 to 24 vectors
tdata <- rawdata[ ,1:24]
names(tdata)

# deal with NAs
tdata[is.na(tdata)] <- 0

# create contigency table by region for matleave_13: data count by length()
num <- tapply(ldata$matleave_13, ldata$region, length)

# tapply() using mean(), sum(), and sd
total <- tapply(ldata$matleave_13, ldata$region, mean)
average <- tapply(ldata$matleave_13, ldata$region, sum)
sd <- tapply(ldata$matleave_13, ldata$region, sd)

# create data frame for about variables
res <- data.frame(num, average, total, sd)
# View(res)

```



# Grouping data: merge rows by category

```{r}
byregion <- aggregate(tdata[,6:24], by=list(tdata$region), mean)
# View(byregion)
byregion.sd <- aggregate(tdata[,6:24], by=list(tdata$region), sd)
?aggregate

head(byregion)

```




# Plotting results

```{r}
# Line ploting the 1st row
dev.off()
plot(unlist(byregion[1,]), type="o")

# Line ploting the 2nd~6th rows
plot(unlist(byregion[2,]), type="o")
plot(unlist(byregion[3,]), type="o")
plot(unlist(byregion[4,]), type="o")
plot(unlist(byregion[5,]), type="o")
plot(unlist(byregion[6,]), type="o")



# Using for-loop and par() to plot all graph
par(mfrow=c(3,2), mai= rep(0.3, 4))
for (i in 1:6){
    plot(unlist(byregion[i,-1]), type="o", ylim=c(0, 5))
	title(byregion[i,1])
}

```
