---
title: "R03_6_POST_ibon"
author: "Jilung Hsieh"
date: "2019/4/26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(httr)
library(rvest)
options(stringsAsFactors = F)
```


# Getting county
```{r}
url <- "http://www.ibon.com.tw/retail_inquiry.aspx#gsc.tab=0"
counties <- read_html(url) %>%
    html_nodes("#Class1 option") %>%
    html_text()
```

# Getting address for each county
```{r}
url <- "http://www.ibon.com.tw/retail_inquiry_ajax.aspx"
res <- POST(url, body = list(strTargetField='COUNTY', 
                             strKeyWords='台北市'))
# cat(content(res, "text"), file="temp.html")
doc <- read_html(content(res, "text"))
addr.node <- html_nodes(doc, "table tr td:nth-child(3)")
# table.node <- html_node(doc, "table")
# html_table(table.node)
addrs <- html_text(addr.node) %>% trimws()
```


```{r}
all_addr <- c()
url <- "http://www.ibon.com.tw/retail_inquiry_ajax.aspx"
for(county in counties){
    res <- POST(url, body = list(strTargetField='COUNTY', 
                             strKeyWords=county))
    doc <- read_html(content(res, "text"))
    addr.node <- html_nodes(doc, "table tr td:nth-child(3)")
    addrs <- html_text(addr.node) %>% trimws()    
    print(sprintf("%s: %d stores", county, length(addrs)))
    all_addr <- c(all_addr, addrs)
}
```

```{r}
library(dplyr)
library(tidyverse)
length(all_addr)
seven <- tibble(addr = all_addr) %>%
    slice(-1) %>%
    mutate(county = str_sub(addr, 1, 3)) %>% 
    filter(!str_detect(addr, "地址")) %>%
    mutate(addr = str_replace(addr, "楠梓加工區", "楠梓區")) %>%
    mutate(town = str_replace(addr, ".*?[縣市](.{1,3}[鄉鎮市區]).*", "\\1")) %>%
    mutate(town = ifelse(nchar(town)==4, str_sub(town, 1, 3), town)) %>%
    mutate(town = str_replace(town, "太麻里", "太麻里鄉"),
           town = str_replace(town, "阿里山", "阿里山鄉"),
           town = str_replace(town, "三地門", "三地門鄉")) %>% 
    # filter(str_detect(town, "東區|南區|北區|中區|西區") & nchar(town)==3) %>%
    mutate(townlen = nchar(town)) %>%
    mutate(site_id = paste0(county, town))
    # filter(townlen == 4) %>% count(town)
```

